### ISSUE TITLE
Demo site is broken

### ISSUE THREAD

**Issue by lgg** [petersamokhin/nodejs-markdown-site#2]
![image](https://user-images.githubusercontent.com/12018713/42187195-e367f266-7e57-11e8-994e-5bbfe37da923.png)

;(

**Comment by petersamokhin** [comment]
Someone renamed `readme.md`, that opened by default on root path, so error occurs.
Fixed :)

**Comment by petersamokhin** [comment]
Someone renamed `readme.md`, that opened by default on root path, so error occurs.
Fixed :)
