### ISSUE TITLE
[Windows] Hardcoded paths error

### ISSUE THREAD

**Issue by sfaqer** [petersamokhin/nodejs-markdown-site#3]
При открытии главной страницы:
![default](https://user-images.githubusercontent.com/32082417/42197481-56b858a0-7ec6-11e8-92c8-0cca339f01f4.png)

Собственно на самом сайте ничего не отображается.
![default](https://user-images.githubusercontent.com/32082417/42197525-85526e9e-7ec6-11e8-9619-a2df7957c55e.png)

**Comment by petersamokhin** [comment]
Какие действия вы совершали для подготовки и для запуска?

В стактрейсе на скриншоте нет кода, принадлежащего проекту, а потому мне трудно узнать, в чём проблема.
Ошибка говорит о том, что где-то два раза вызывается `res.send`, либо он вызывается после ошибки.

Буду очень благодарен, если опишете шаги для воспроизведения ошибки полностью.

**Comment by petersamokhin** [comment]
Какие действия вы совершали для подготовки и для запуска?

В стактрейсе на скриншоте нет кода, принадлежащего проекту, а потому мне трудно узнать, в чём проблема.
Ошибка говорит о том, что где-то два раза вызывается res.send, либо он вызывается после ошибки.

Буду очень благодарен, если опишете шаги для воспроизведения ошибки полностью.

**Comment by sfaqer** [comment]
Шаги как описаны в readme к проекту. 

1. Установил зависимости: 
    1. NodeJS (+ npm)
    1. MongoDB (used for passport sessions, user and paths info)
    1. Ruby (for kramdown library)
    1. babel

2. 
``` 
git clone https://github.com/petersamokhin/markdown-site
``` 
3.
``` 
npm i
``` 
4.
``` 
npm run rebuild
``` 
5.
``` 
npm start
```

Собственно при открытии страницы: http://localhost:3006/markdown-site , авторизуюсь, и на главной странице пусто, а в стактрейсе 500.

**Comment by sfaqer** [comment]
Дополню по поводу 

```
npm i
```
Кидает ворн на скип опциональной зависимости на win10, насколько я понял это не критично, но для справки приведу.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by petersamokhin** [comment]
А, Windows...
Я попозже постараюсь эту проблему решить и унифицировать вызов ruby-скриптов, а пока скажу вам, как решить проблему:

Утилита, преобразующая Markdown в HTML работает на ruby, и у меня захардкожен вызов этой утилиты и самого ruby:

https://github.com/petersamokhin/nodejs-markdown-site/blob/master/lib/utils/kramdown.js#L16

Как решить эту проблему:

1. Убедитесь, установлен ли у вас Ruby.
2. Проверьте, добавлен ли он в PATH (или куда на Windows добавляются глобальные пути?), либо захардкодьте полный путь до исполняемого файла ruby.
3. Проверьте, установлен ли у вас `kramdown` и замените (абсолютный!) путь до него на нужный (у вас будет не `/usr/local/bin/kramdown`).

**Comment by petersamokhin** [comment]
А, Windows...
Я попозже постараюсь эту проблему решить и унифицировать вызов ruby-скриптов, а пока скажу вам, как решить проблему:

Утилита, преобразующая Markdown в HTML работает на ruby, и у меня захардкожен вызов этой утилиты и самого ruby:

https://github.com/petersamokhin/nodejs-markdown-site/blob/master/lib/utils/kramdown.js#L16

Как решить эту проблему:

1. Убедитесь, установлен ли у вас Ruby.
2. Проверьте, добавлен ли он в PATH (или куда на Windows добавляются глобальные пути?), либо захардкодьте полный путь до исполняемого файла ruby — 17-я и 34-я строчки файла, ссылка на который чуть выше.
3. Проверьте, установлен ли у вас `kramdown` и замените (абсолютный!) путь до него на нужный (у вас будет не `/usr/local/bin/kramdown`) — 16-я строчка файла, ссылка на который чуть выше.

**Comment by sfaqer** [comment]
> 1. Убедитесь, установлен ли у вас Ruby.
> 1. Проверьте, добавлен ли он в PATH (или куда на Windows добавляются глобальные пути?), либо захардкодьте полный путь до исполняемого файла ruby — 17-я и 34-я строчки файла, ссылка на который чуть выше.

Да, это я проделал ещё до открытия issue. 

>3. Проверьте, установлен ли у вас kramdown и замените (абсолютный!) путь до него на нужный (у вас будет не /usr/local/bin/kramdown) — 16-я строчка файла, ссылка на который чуть выше.

Спасибо! Как раз то что нужно.) Ошибка ушла, страницы начали открываться. 

Теперь правда ещё возник вопрос на тему навигации (точнее её отсутствия):

![default](https://user-images.githubusercontent.com/32082417/42296357-443c0794-8038-11e8-847f-1816219f4686.png)

Почему она может не формироваться?

**Comment by petersamokhin** [comment]
Скорее всего она не формируется потому что нет информации в базе данных, возможно она стёрлась или что-то ещё пошло не так.
Попробуйте вручную перейти по какому-нибудь адресу (путь `localhost:3006/markdown-site/pages/` соответствует пути на диске `lib/views/pages`, соответственно отрезаете начальную часть от пути на диске и получаете конечную часть ссылки на страницу).

Как фиксить — можно попробовать вручную (через Studio 3T — gui над Mongo, или же вручную через shell) поправить права и добавить права для недостающих страниц, или же добавить дебаг-логгинг в том месте, где навигация генерируется.

Происходит вся магия здесь:

https://github.com/petersamokhin/nodejs-markdown-site/blob/2cce6c1dfd3e2170c0a09e2ba64cd9b1847213c0/lib/utils/generate-table-of-contents.js#L10-L22

`tree` — дерево файлов в нужной папке, `map` — словарь, где ключом выступает путь до файла/папки, а значением `true` или `false` в зависимости от прав пользователя (может он видеть этот путь или нет).

Попробуйте и то и то залоггировать, с этого можно начать.
Возможно на каком-то из родительских путей сбились доступы, или их вовсе нет (скорее всего, косячно выставляются пути при первом запуске).

Права `reader` (или какие вы решите выдавать, или любые другие) должны быть у всех родительских путей — `/`, `/pages` и так далее, убедитесь в этом, скорее всего здесь и кроется проблема.

А я постараюсь попробовать тоже с нуля поднять проект, возможно те же артефакты появятся (когда на сервере поднимал демо, проблем не было, как ни странно).

Спасибо!

**Comment by sfaqer** [comment]
хм, а он мог в слэшах запутаться?
![default](https://user-images.githubusercontent.com/32082417/42311131-75500072-8080-11e8-8fa6-8584bc21ec37.png)

**Comment by petersamokhin** [comment]
Скорее всего, проблема в путях, т.к. сравниваются уже просто строки.
Попробуйте накостылить замену `\\` на `/` во всех путях, я потом постараюсь поправить.
И ещё добавьте права доступа для `/` и `/pages` на всякий случай.

**Comment by petersamokhin** [comment]
Я не смогу проверить работоспособность путей на Windows, попробуйте в местах, где пути с диска берутся в строку (в частности рекурсивно во всех детях объекта`tree`).
Буду крайне благодарен, если напишете о результате.

**Comment by sfaqer** [comment]
Просто подмены в путях оказалось недостаточно, т.к. в ```map.get()``` доходит абсолютный путь до файла\каталога, а в ```map``` лежит относительный путь.
Наличие\отсутствие прав на ```/``` и ```/pages``` в целом не оказало никакого влияния. 
В моём случае помог вот такой костыль:
![default](https://user-images.githubusercontent.com/32082417/42352955-f2be1406-8100-11e8-82a2-8d47035969f4.png)

Спасибо!

**Comment by petersamokhin** [comment]
Странно, у меня работало на разных системах, а я и не обратил внимания на абсолютные пути, видимо. Исправлю.
Теперь у вас все работает без проблем?

**Comment by sfaqer** [comment]
В этой части да.) Потенциально нашёл проблему в "админке" на тему выдачи новых ролей, но я это оформлю отдельными issue, как оттестирую нормально.

**Comment by petersamokhin** [comment]
Отлично, это issue я закрою дабы дальше его не захламлять, т.к. проблема выглядит решённой.

Спасибо за интерес, отвечу на все issues и рассмотрю все PR.
