### ISSUE TITLE
Bold and Strikethrough text issue

### ISSUE THREAD

**Issue by sfaqer** [petersamokhin/nodejs-markdown-site#4]
Не отрабатывает выделение **Bold** и ~~Strikethrough~~

**Comment by petersamokhin** [comment]
Проверил, отрабатывает: https://petersamokhin.com/markdown-site/pages/Main%20articles/111

Скриншот:
<img src="https://i.imgur.com/yN3XbuJ.png" width="300"></img>

Исходный `111.md`:
```markdown
# Article text

**test**

~~test~~
```

**Comment by sfaqer** [comment]
Со Strikethrough поторопился, отрабатывает, а вот болд даже по ссылке не видно:
![default](https://user-images.githubusercontent.com/32082417/42363973-e476e2d8-813c-11e8-97e3-294f858090d1.png)

**Comment by petersamokhin** [comment]
Если вглядеться, разница видна 🤔

![](https://i.imgur.com/afdzFaR.png)

Возможно, что-то со стилями вашего браузера и т.д. — у меня, хоть и слабо, но заметно разницу. Сделаю чуть потолще, но вам могу посоветовать только попробовать через другие браузеры страницу просмотреть. А ещё можете через код страницы проверить — жирный текст должен быть обрамлён тегом `strong`.

**Comment by sfaqer** [comment]
Правила css выглядят вот так:
![default](https://user-images.githubusercontent.com/32082417/42366342-49bd756a-8144-11e8-9c84-cebeed43f599.png)

Что примечательно, если отключить font-weight: 500, то визуально становится болдом =)
![default](https://user-images.githubusercontent.com/32082417/42366429-818c93cc-8144-11e8-93fa-2fcaeb5a8b69.png)

Тег strong присутствует, так что да, я неверно диагностировал проблему.

**Comment by petersamokhin** [comment]
Вполне возможно, что стили `materialize` опять конфликтуют со стилями для отображения Markdown-страницы, взятыми с сайта документации Kotlin. Я и так многое подправлял, а на это не обратил внимания. Спасибо ещё раз!
